GraceShopper8/GraceShopper8

client/store/product.js
=> fix(store/product): fixes reducer on product

package-lock.json, package.json, server/api/index.js, server/api/products.js, server/api/users.js
Product api routes now also attach review data to the response
=> Products route include reviews

server/api/users.js
=> feat(routes): user routes created

client/components/Cart.js, client/store/cart.js
=> feat(cart): fixed broken splice formula

client/components/Cart.js, client/components/navbar.js, public/style.css
=> New styling

client/components/Cart.js, client/components/navbar.js, public/style.css
=> Styling update

client/components/LandingPage.js, server/db/models/user.js
=> feat(LandingPage): title fix

client/components/ProductList.js, client/components/createUserForm.js, client/components/user-home.js, client/store/product.js, client/store/user.js
made little changes and made sure that the user stays loggined aftr registering
=> feat(signup): able to stay loggedin

client/components/Cart.js
Removes some of the confusion caused by me & beth working through the cart thing yesterday
=> feat(cart): adjusts cart to just grab local storage and add to db

client/components/ProductDetail.js
=> feat(product-detail): removes redundant buttons

client/components/Cart.js, client/components/Checkout.js, client/components/stripe/CheckoutForm.js, client/store/cart.js, client/store/index.js, client/store/order.js, client/store/product.js, server/api/index.js, server/api/orders.js, server/api/products.js, server/db/models/Order.js
feat(stripe): stripe checkout now has access to cart items total price via store
=> feat(stripe): stripe checkout now has access to cart items total price

client/components/stripe/AddressSection.js, client/components/stripe/CheckoutForm.js, client/components/stripe/Receipt.js, client/store/index.js, client/store/receipt.js, package-lock.json, public/style.css, server/api/checkout.js, server/api/index.js
Payment goes through successfully and DB populates appropriately.
=> Posting order

client/components/AdminEditForm.js, client/components/UserReviewForm.js, package-lock.json, package.json, public/style.css
=> Add review

client/components/navbar.js, public/index.html, public/style.css
=> fix(navbar): Changed design implementation

client/components/AdminEditForm.js, client/components/ProductList.js, client/components/editUserForm.js, client/store/product.js, package-lock.json, server/auth/index.js, server/db/models/user.js
Added inventory Edit field to AdminEditForm 
Competed UserEdit form to prepopulate with the currentUser information 
Completed live validation checks for email, and user can edit password functionality,
Competed filter category functionality
---
=> Add inventory

client/components/AdminEditForm.js, client/components/ProductList.js, client/components/editUserForm.js, server/auth/index.js
=> Filter drop down

client/components/navbar.js, client/routes.js, public/style.css
feat(nav-bar): adjusted formatting (not fixed, no top margin)
=> feat(nav-bar): adjusted formatting (not fixed, no top margin)

server/auth/google.js, server/db/models/user.js
feat(OAuth): adjusted to grab user first and last name when signing in with google
=> Google o auth

client/components/ProductCard.js, client/components/ProductDetail.js, client/components/ProductList.js, client/components/navbar.js, client/store/checkout.js, client/store/index.js, script/seed-files/productData.js, script/seed-files/reviewData.js, script/seed-files/userData.js, server/api/checkout.js, server/api/products.js, server/db/models/Order.spec.js, server/index.js, server/socket/index.js
=> fix(eslint): fixed majority of eslint warnings and errors

client/index.js, client/routes.js, client/socket.js, public/index.html, server/index.js
=> fix(cleanUp): deleted console.log, fixed favicon links

client/routes.js, client/store/order.spec.js, server/db/models/Review.spec.js
- added orders store spec tests,
review models tests,
took out loading div's
---
=> Store tests
